name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run PowerShell command
        shell: powershell
        run: |
          # Your PowerShell commands go here
          $currentPath = Get-Location -PSProvider FileSystem | Select-Object -ExpandProperty Path
          Write-Host "Current Path: $currentPath

