name: CI

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up S3cmd cli tool
        uses: s3-actions/s3cmd@v1.5.0
        with:
          provider: aws # default is linode
          region: 'ap-south-1'
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}


      - name: Publish to S3
        run: | 
            PWD
            aws s3 sync .\src s3://nsybucket --delete
        
          
     

