name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run PowerShell command
        run: |
          # Your PowerShell commands go here
          $PWD.Path
          Copy-Item -Path ".\src*" -Destination "C:\inetpub\dsdevops" -Recurse

      # Add more steps as needed

