name: CI

on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy files
        shell: cmd
        run: |
          # Copy folders and files using the xcopy command
          xcopy ".\src\" "C:\inetpub\dsdevops" /E /I /Y



